dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - doxygen

install:
  - pip install --user conan cmake


script:
  - CC=gcc CXX=g++ cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j
  - ctest -j
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5
